/**
 * Hand-picked, tool-specific search keywords used to enrich each tool page's
 * <meta name="keywords"> and JSON-LD. English and Indonesian phrases are kept
 * as separate lists (not interleaved) so each language reads as its own
 * coherent block when rendered. Keyed by Tool.id (see lib/tools.ts).
 */
export interface ToolKeywordSet {
  en: string[];
  id: string[];
}

export const TOOL_KEYWORDS: Record<string, ToolKeywordSet> = {
  // --- IMAGE ---
  "remove-bg": {
    en: [
      "remove background",
      "ai background remover",
      "remove image background online",
      "transparent background maker",
      "background eraser tool",
      "erase photo background",
      "cutout image background free",
      "auto background remover",
      "png background remover",
      "photo background remover ai",
      "clear background from picture",
    ],
    id: [
      "hapus background foto",
      "hapus latar belakang gambar",
      "hapus background otomatis",
      "buat background transparan",
      "hilangkan background foto online",
      "hapus bg foto gratis",
      "aplikasi hapus background online",
      "ganti background foto jadi transparan",
      "hapus background pas foto",
      "cara hapus background foto online",
      "buat foto transparan online",
    ],
  },
  "image-converter": {
    en: [
      "image converter",
      "convert image format online",
      "jpg to png converter",
      "png to jpg converter",
      "webp converter",
      "heic to jpg converter",
      "avif converter",
      "image file format converter free",
      "convert photo to different format",
      "batch image format converter",
      "jpeg to webp converter",
    ],
    id: [
      "convert gambar online",
      "ubah format gambar",
      "ubah foto ke png",
      "ubah foto ke jpg",
      "konversi format gambar gratis",
      "ganti ekstensi gambar online",
      "convert foto heic ke jpg",
      "ubah tipe file gambar",
      "convert foto ke webp",
      "convert semua format gambar",
      "ganti format foto online gratis",
    ],
  },
  "image-resizer": {
    en: [
      "image resizer",
      "resize image online",
      "resize photo free",
      "change image dimensions",
      "photo resizer pixels",
      "batch image resize",
      "resize image to specific size",
      "resize picture without losing quality",
      "resize image for instagram",
    ],
    id: [
      "resize gambar online",
      "ubah ukuran foto",
      "perkecil ukuran foto online",
      "ubah resolusi gambar",
      "resize foto ke ukuran tertentu",
      "kecilkan dimensi gambar gratis",
      "ubah ukuran foto online gratis",
      "resize foto pas foto",
      "kecilkan resolusi gambar online",
    ],
  },
  "image-compressor": {
    en: [
      "image compressor",
      "compress image online",
      "reduce image file size",
      "compress photo without losing quality",
      "compress jpg online",
      "compress png online",
      "shrink image size free",
      "compress image to kb",
      "bulk image compressor",
      "optimize image for web",
    ],
    id: [
      "kompres gambar online",
      "kompres foto online",
      "perkecil ukuran gambar",
      "kompres foto tanpa mengurangi kualitas",
      "kompres foto ke ukuran kb",
      "kecilkan ukuran file gambar gratis",
      "kompres foto jpg png",
      "perkecil size foto online",
      "kompres foto untuk upload",
      "kompres banyak foto sekaligus",
    ],
  },
  "image-cropper": {
    en: [
      "image cropper",
      "crop image online",
      "crop photo free",
      "aspect ratio crop tool",
      "square image cropper",
      "crop photo for instagram",
      "crop picture online free",
      "crop image to size",
    ],
    id: [
      "potong gambar online",
      "potong foto online gratis",
      "crop foto ke rasio tertentu",
      "potong foto persegi",
      "crop foto untuk profil",
      "potong foto online mudah",
      "crop foto pas foto online",
      "potong bagian gambar online",
    ],
  },
  "image-splitter": {
    en: [
      "image splitter",
      "split image into grid",
      "instagram grid maker",
      "split photo into pieces",
      "image grid divider",
      "9 grid image splitter",
      "split picture into parts free",
    ],
    id: [
      "potong gambar jadi grid",
      "bagi foto jadi beberapa bagian",
      "buat grid instagram online",
      "pecah gambar jadi puzzle",
      "split foto jadi 9 kotak",
      "buat feed grid instagram online",
      "potong satu foto jadi banyak",
    ],
  },
  "image-draw": {
    en: [
      "draw on image online",
      "annotate photo online",
      "add drawing to image",
      "photo markup tool",
      "image annotation tool free",
      "sketch on picture online",
      "paint on photo online",
      "add text and shapes to image",
    ],
    id: [
      "gambar di atas foto",
      "coret coret foto online",
      "tambah anotasi ke gambar",
      "edit foto dengan gambar tangan",
      "tulis di atas gambar online",
      "edit gambar pakai pensil online",
      "tambah panah dan bentuk ke gambar",
      "coret foto online gratis",
    ],
  },
  "color-picker-image": {
    en: [
      "color picker from image",
      "eyedropper tool online",
      "get hex color from image",
      "image color picker free",
      "pick color code from photo",
      "extract color from picture",
      "color code finder from image",
      "rgb picker from photo",
    ],
    id: [
      "ambil warna dari gambar",
      "cari kode warna dari foto",
      "pipet warna online",
      "deteksi warna dari gambar",
      "ambil kode hex dari foto",
      "cari warna dominan gambar",
      "cek kode rgb dari gambar",
      "pipet warna dari foto online",
    ],
  },
  "metadata-viewer": {
    en: [
      "image metadata viewer",
      "exif data viewer online",
      "view photo exif online",
      "check image metadata free",
      "exif reader online",
      "camera info from photo",
      "gps location from photo exif",
      "view photo capture date",
    ],
    id: [
      "lihat metadata foto",
      "cek data exif foto",
      "lihat lokasi gps dari foto",
      "cek info kamera dari foto",
      "cek exif kamera online",
      "lihat tanggal foto diambil",
      "lihat data teknis foto",
      "cek metadata gambar gratis",
    ],
  },
  "svg-tracer": {
    en: [
      "svg tracer online",
      "image to svg converter",
      "convert png to svg",
      "vectorize image online",
      "raster to vector converter",
      "trace image to vector free",
      "photo to vector converter",
      "convert logo to svg",
    ],
    id: [
      "ubah gambar ke svg",
      "vektorkan gambar online",
      "convert foto ke vector gratis",
      "buat logo vector online",
      "ubah gambar jadi file vector",
      "trace logo ke svg online",
      "vektor gambar tanpa aplikasi",
    ],
  },
  watermark: {
    en: [
      "add watermark to image",
      "watermark maker online",
      "photo watermark tool free",
      "text watermark generator",
      "logo watermark on image",
      "protect photo with watermark",
      "bulk watermark images online",
      "add copyright to photo",
    ],
    id: [
      "tambah watermark foto",
      "buat watermark online",
      "kasih watermark ke gambar",
      "watermark foto gratis",
      "buat watermark logo online",
      "pasang watermark ke banyak foto",
      "watermark teks di foto online",
      "lindungi foto dengan watermark",
    ],
  },
  twibbon: {
    en: [
      "twibbon maker",
      "twibbon generator free",
      "campaign photo frame maker",
      "twibbon creator online",
      "profile picture frame maker",
      "event photo frame generator",
    ],
    id: [
      "buat twibbon online",
      "frame foto twibbon",
      "twibbon gratis online",
      "bikin twibbon sendiri",
      "twibbon acara online",
      "buat bingkai foto kampanye online",
    ],
  },
  photobooth: {
    en: [
      "online photobooth",
      "web photobooth free",
      "photo booth camera online",
      "photostrip maker online",
      "photobooth strip generator",
      "webcam photobooth free",
      "take photo online with filters",
    ],
    id: [
      "photobooth online gratis",
      "kamera photobooth online",
      "buat photostrip online",
      "foto strip online gratis",
      "foto pakai kamera laptop online",
      "photobooth gratis tanpa aplikasi",
      "buat foto strip lucu online",
    ],
  },
  "qr-generator": {
    en: [
      "qr code generator",
      "free qr code maker",
      "generate qr code from url",
      "wifi qr code generator",
      "custom qr code with logo",
      "qr code creator free",
      "vcard qr code generator",
      "qr code for business card",
    ],
    id: [
      "buat qr code online",
      "buat kode qr gratis",
      "generator qr code online",
      "qr code wifi gratis",
      "buat qr code untuk wifi",
      "qr code untuk kartu nama online",
      "buat barcode qr gratis",
      "qr code custom dengan logo online",
    ],
  },
  "qr-scanner": {
    en: [
      "qr code scanner online",
      "scan qr code from image",
      "decode qr code online",
      "qr code reader free",
      "upload qr code to scan",
      "qr code decoder online",
      "read qr code from photo",
    ],
    id: [
      "baca qr code online",
      "scan qr code dari gambar",
      "pindai qr code gratis",
      "scan barcode qr dari foto",
      "baca kode qr tanpa aplikasi",
      "upload gambar qr untuk dibaca",
      "decode qr code dari gambar online",
    ],
  },

  // --- UNIT ---
  "unit-converter": {
    en: [
      "unit converter online",
      "convert length weight temperature",
      "metric to imperial converter",
      "convert km to miles",
      "unit converter free tool",
      "convert volume area speed",
      "convert celsius to fahrenheit",
    ],
    id: [
      "konversi satuan online",
      "ubah satuan panjang berat",
      "konversi ukuran gratis",
      "konversi panjang berat suhu",
      "ubah km ke mil online",
      "konversi celcius ke fahrenheit",
      "alat konversi satuan gratis",
    ],
  },
  "data-converter": {
    en: [
      "data storage converter",
      "convert mb to gb",
      "byte converter online",
      "kb mb gb tb converter",
      "digital storage unit converter",
      "file size converter free",
      "convert bytes to gigabytes",
    ],
    id: [
      "konversi ukuran file",
      "ubah satuan penyimpanan data",
      "konversi byte ke gb",
      "ubah mb ke gb online",
      "konversi kb ke mb gratis",
      "hitung ukuran penyimpanan digital",
      "alat konversi byte online",
    ],
  },

  // --- TEXT ---
  "case-converter": {
    en: [
      "case converter online",
      "text case converter",
      "uppercase to lowercase converter",
      "title case generator",
      "convert text to sentence case",
      "camel case converter",
      "snake case generator online",
      "capitalize text online",
    ],
    id: [
      "ubah huruf besar kecil",
      "ubah teks jadi huruf kapital",
      "konversi teks online",
      "ubah teks jadi title case",
      "konversi teks ke huruf kecil",
      "ubah teks ke camel case online",
      "kapitalisasi teks otomatis",
    ],
  },
  "word-counter": {
    en: [
      "word counter online",
      "character counter online",
      "count words in text",
      "text length counter",
      "word count tool free",
      "sentence and paragraph counter",
      "count characters in paragraph",
    ],
    id: [
      "hitung jumlah kata",
      "hitung karakter teks online",
      "penghitung kata gratis",
      "hitung kalimat dan paragraf",
      "cek jumlah karakter tulisan",
      "hitung panjang teks online",
    ],
  },
  "lorem-ipsum": {
    en: [
      "lorem ipsum generator",
      "placeholder text generator",
      "dummy text generator online",
      "generate lorem ipsum free",
      "fake text generator",
      "filler text generator online",
      "sample text generator for design",
    ],
    id: [
      "generator teks lorem ipsum",
      "buat teks dummy online",
      "teks placeholder gratis",
      "buat teks isian desain",
      "teks pengisi konten gratis",
      "buat kalimat dummy online",
    ],
  },
  "markdown-previewer": {
    en: [
      "markdown previewer online",
      "markdown to html converter",
      "live markdown editor",
      "preview markdown online",
      "md file viewer free",
      "markdown editor online",
      "render markdown live",
    ],
    id: [
      "preview markdown online",
      "editor markdown gratis",
      "lihat hasil markdown online",
      "ubah markdown ke html online",
      "tulis dan lihat markdown langsung",
      "cek tampilan file md online",
    ],
  },
  "text-diff": {
    en: [
      "text diff checker",
      "compare two texts online",
      "diff tool free",
      "text comparison tool",
      "find difference between text",
      "line by line text compare",
      "compare documents online",
    ],
    id: [
      "bandingkan dua teks online",
      "cek perbedaan teks",
      "perbandingan dokumen online",
      "cek selisih dua dokumen",
      "bandingkan kode program online",
      "cari kata yang berubah di teks",
    ],
  },

  // --- MATH ---
  "percentage-calculator": {
    en: [
      "percentage calculator online",
      "calculate percentage free",
      "percent increase decrease calculator",
      "percentage of a number calculator",
      "discount percentage calculator",
      "percentage change calculator",
    ],
    id: [
      "hitung persen online",
      "kalkulator persen gratis",
      "hitung diskon persen",
      "hitung kenaikan persen online",
      "kalkulator diskon belanja",
      "hitung persen dari angka",
    ],
  },
  "age-calculator": {
    en: [
      "age calculator online",
      "calculate age from date of birth",
      "birthday age calculator",
      "age in years months days calculator",
      "how old am i calculator",
      "date of birth age calculator",
    ],
    id: [
      "hitung umur online",
      "kalkulator usia gratis",
      "hitung umur dari tanggal lahir",
      "kalkulator ulang tahun gratis",
      "cek umur dalam hari online",
      "hitung usia dari tanggal lahir online",
    ],
  },
  "bmi-calculator": {
    en: [
      "bmi calculator online",
      "body mass index calculator",
      "calculate bmi metric imperial",
      "ideal weight calculator",
      "bmi chart calculator free",
      "check bmi online",
    ],
    id: [
      "hitung bmi online",
      "kalkulator berat badan ideal",
      "cek indeks massa tubuh",
      "kalkulator imt online",
      "cek berat badan ideal gratis",
      "hitung bmi metrik dan imperial",
    ],
  },
  "tip-calculator": {
    en: [
      "tip calculator online",
      "split bill calculator",
      "calculate tip and split bill",
      "bill splitter tool free",
      "gratuity calculator online",
      "restaurant bill calculator",
    ],
    id: [
      "hitung tip restoran",
      "kalkulator patungan bayar",
      "bagi tagihan online",
      "hitung tip makan online",
      "kalkulator bagi rata tagihan",
      "hitung service charge restoran",
    ],
  },

  // --- COLOR ---
  "color-picker": {
    en: [
      "color picker online",
      "hex color picker",
      "rgb color picker free",
      "pick color code online",
      "color code generator",
      "hsl color picker tool",
      "cmyk color picker online",
    ],
    id: [
      "pilih warna online",
      "cari kode warna hex",
      "alat pemilih warna gratis",
      "cari kode warna rgb online",
      "alat konversi kode warna",
      "pilih warna hex gratis",
      "cek kode warna cmyk online",
    ],
  },
  "color-palette": {
    en: [
      "color palette generator",
      "generate color scheme online",
      "hex color palette maker",
      "random color palette generator",
      "color combination tool free",
      "palette generator for design",
      "generate matching colors",
    ],
    id: [
      "buat palet warna online",
      "generator skema warna gratis",
      "kombinasi warna otomatis",
      "buat kombinasi warna desain",
      "generator warna acak online",
      "cari palet warna serasi",
      "buat skema warna website",
    ],
  },
  "gradient-generator": {
    en: [
      "css gradient generator",
      "linear gradient maker online",
      "radial gradient generator",
      "gradient color picker",
      "generate css background gradient",
      "gradient css code generator",
    ],
    id: [
      "buat gradasi warna css",
      "generator gradasi warna online",
      "kode css gradient gratis",
      "buat kode gradasi css online",
      "kombinasi warna gradient css",
    ],
  },
  "contrast-checker": {
    en: [
      "color contrast checker",
      "wcag contrast checker online",
      "accessibility contrast ratio tool",
      "check text background contrast",
      "contrast ratio calculator free",
      "aa aaa contrast checker",
    ],
    id: [
      "cek kontras warna online",
      "alat cek aksesibilitas warna",
      "rasio kontras teks gratis",
      "cek rasio kontras teks online",
      "cek warna sesuai standar wcag",
    ],
  },

  // --- DEV ---
  "json-formatter": {
    en: [
      "json formatter online",
      "json beautifier free",
      "json validator online",
      "format json online",
      "minify json online",
      "json pretty print",
      "json editor and viewer",
    ],
    id: [
      "format json online",
      "rapikan json gratis",
      "validasi json online",
      "beautify json online gratis",
      "cek format json valid",
      "perkecil ukuran json online",
      "editor json online gratis",
    ],
  },
  "base64-encoder": {
    en: [
      "base64 encoder decoder online",
      "encode text to base64",
      "decode base64 online",
      "base64 to image converter",
      "base64 converter free",
      "encode image to base64",
    ],
    id: [
      "encode teks ke base64",
      "decode base64 online gratis",
      "konversi base64 ke gambar",
      "ubah gambar ke base64",
      "alat konversi base64 online",
    ],
  },
  "password-generator": {
    en: [
      "password generator online",
      "strong random password generator",
      "secure password maker",
      "generate password free",
      "random password generator tool",
      "create strong password online",
    ],
    id: [
      "buat password acak",
      "generator password gratis",
      "buat kata sandi kuat online",
      "buat sandi acak online",
      "generator kata sandi aman",
      "buat password sulit ditebak",
    ],
  },
  "hash-generator": {
    en: [
      "hash generator online",
      "md5 hash generator",
      "sha256 hash calculator",
      "generate hash from text",
      "checksum calculator free",
      "hash text online",
    ],
    id: [
      "generator hash online",
      "hitung md5 sha256 gratis",
      "buat checksum online",
      "hitung hash md5 online",
      "buat checksum file gratis",
      "generator sha256 online",
    ],
  },
  "timestamp-converter": {
    en: [
      "unix timestamp converter",
      "epoch converter online",
      "timestamp to date converter",
      "convert unix time to date",
      "epoch time calculator",
      "unix time to human readable date",
    ],
    id: [
      "konversi timestamp online",
      "ubah unix time ke tanggal",
      "kalkulator epoch time",
      "ubah epoch time ke tanggal",
      "konversi waktu unix online",
      "kalkulator waktu unix gratis",
    ],
  },
  "url-encoder": {
    en: [
      "url encoder decoder online",
      "encode url free",
      "decode url string online",
      "percent encoding tool",
      "uri encoder online",
      "encode special characters in url",
    ],
    id: [
      "encode url online",
      "decode url gratis",
      "alat encode karakter url",
      "encode karakter khusus url",
      "decode string url online",
      "alat konversi url gratis",
    ],
  },
  "uuid-generator": {
    en: [
      "uuid generator online",
      "generate random uuid v4",
      "guid generator free",
      "bulk uuid generator",
      "unique id generator tool",
      "generate multiple uuids",
    ],
    id: [
      "generator uuid online",
      "buat id unik gratis",
      "buat uuid v4 online",
      "buat guid online gratis",
      "generator id unik banyak sekaligus",
      "buat uuid random online",
    ],
  },
  "regex-tester": {
    en: [
      "regex tester online",
      "regular expression tester",
      "test regex pattern free",
      "regex match checker",
      "javascript regex tester online",
      "regex pattern debugger",
    ],
    id: [
      "tester regex online",
      "uji ekspresi reguler gratis",
      "cek pola regex online",
      "cek pola ekspresi reguler",
      "uji regex javascript online",
      "debug regex pattern gratis",
    ],
  },
  "number-base-converter": {
    en: [
      "number base converter",
      "binary to decimal converter",
      "hex to decimal converter online",
      "convert binary hex octal",
      "base converter tool free",
      "decimal to binary converter online",
    ],
    id: [
      "konversi basis angka",
      "ubah biner ke desimal",
      "konversi angka heksadesimal",
      "konversi desimal ke biner online",
      "ubah heksadesimal ke desimal",
      "konversi biner oktal heksadesimal",
    ],
  },
  "jwt-decoder": {
    en: [
      "jwt decoder online",
      "decode jwt token",
      "jwt token viewer",
      "inspect jwt claims",
      "json web token decoder free",
      "verify jwt payload online",
    ],
    id: [
      "decode token jwt online",
      "lihat isi jwt gratis",
      "cek payload jwt online",
      "cek isi token jwt online",
      "lihat header dan payload jwt",
      "decode json web token gratis",
    ],
  },
  "html-viewer": {
    en: [
      "html viewer online",
      "html previewer free",
      "render html code online",
      "html to preview converter",
      "live html editor online",
      "test html code online",
    ],
    id: [
      "preview html online",
      "lihat hasil kode html",
      "editor html online gratis",
      "jalankan kode html online",
      "tes tampilan html langsung",
      "editor html live gratis",
    ],
  },
};
