/**
 * Hand-picked, tool-specific search keywords used to enrich each tool page's
 * <meta name="keywords"> and JSON-LD. English and Indonesian phrases are kept
 * as separate lists (not interleaved) so each language reads as its own
 * coherent block when rendered. Keyed by Tool.id (see lib/tools.ts).
 */
export interface ToolKeywordSet {
  en: string[];
  id: string[];
}

export const TOOL_KEYWORDS: Record<string, ToolKeywordSet> = {
  // --- IMAGE ---
  "remove-bg": {
    en: [
      "remove background",
      "ai background remover",
      "remove image background online",
      "transparent background maker",
      "background eraser tool",
      "erase photo background",
      "cutout image background free",
      "auto background remover",
      "png background remover",
      "photo background remover ai",
      "clear background from picture",
    ],
    id: [
      "hapus background foto",
      "hapus latar belakang gambar",
      "hapus background otomatis",
      "buat background transparan",
      "hilangkan background foto online",
      "hapus bg foto gratis",
      "aplikasi hapus background online",
      "ganti background foto jadi transparan",
      "hapus background pas foto",
      "cara hapus background foto online",
      "buat foto transparan online",
    ],
  },
  "image-converter": {
    en: [
      "image converter",
      "convert image format online",
      "jpg to png converter",
      "png to jpg converter",
      "webp converter",
      "heic to jpg converter",
      "avif converter",
      "image file format converter free",
      "convert photo to different format",
      "batch image format converter",
      "jpeg to webp converter",
    ],
    id: [
      "convert gambar online",
      "ubah format gambar",
      "ubah foto ke png",
      "ubah foto ke jpg",
      "konversi format gambar gratis",
      "ganti ekstensi gambar online",
      "convert foto heic ke jpg",
      "ubah tipe file gambar",
      "convert foto ke webp",
      "convert semua format gambar",
      "ganti format foto online gratis",
    ],
  },
  "image-resizer": {
    en: [
      "image resizer",
      "resize image online",
      "resize photo free",
      "change image dimensions",
      "photo resizer pixels",
      "batch image resize",
      "resize image to specific size",
      "resize picture without losing quality",
      "resize image for instagram",
    ],
    id: [
      "resize gambar online",
      "ubah ukuran foto",
      "perkecil ukuran foto online",
      "ubah resolusi gambar",
      "resize foto ke ukuran tertentu",
      "kecilkan dimensi gambar gratis",
      "ubah ukuran foto online gratis",
      "resize foto pas foto",
      "kecilkan resolusi gambar online",
    ],
  },
  "image-compressor": {
    en: [
      "image compressor",
      "compress image online",
      "reduce image file size",
      "compress photo without losing quality",
      "compress jpg online",
      "compress png online",
      "shrink image size free",
      "compress image to kb",
      "bulk image compressor",
      "optimize image for web",
    ],
    id: [
      "kompres gambar online",
      "kompres foto online",
      "perkecil ukuran gambar",
      "kompres foto tanpa mengurangi kualitas",
      "kompres foto ke ukuran kb",
      "kecilkan ukuran file gambar gratis",
      "kompres foto jpg png",
      "perkecil size foto online",
      "kompres foto untuk upload",
      "kompres banyak foto sekaligus",
    ],
  },
  "image-cropper": {
    en: [
      "image cropper",
      "crop image online",
      "crop photo free",
      "aspect ratio crop tool",
      "square image cropper",
      "crop photo for instagram",
      "crop picture online free",
      "crop image to size",
    ],
    id: [
      "potong gambar online",
      "potong foto online gratis",
      "crop foto ke rasio tertentu",
      "potong foto persegi",
      "crop foto untuk profil",
      "potong foto online mudah",
      "crop foto pas foto online",
      "potong bagian gambar online",
    ],
  },
  "image-splitter": {
    en: [
      "image splitter",
      "split image into grid",
      "instagram grid maker",
      "split photo into pieces",
      "image grid divider",
      "9 grid image splitter",
      "split picture into parts free",
    ],
    id: [
      "potong gambar jadi grid",
      "bagi foto jadi beberapa bagian",
      "buat grid instagram online",
      "pecah gambar jadi puzzle",
      "split foto jadi 9 kotak",
      "buat feed grid instagram online",
      "potong satu foto jadi banyak",
    ],
  },
  "image-draw": {
    en: [
      "draw on image online",
      "annotate photo online",
      "add drawing to image",
      "photo markup tool",
      "image annotation tool free",
      "sketch on picture online",
      "paint on photo online",
      "add text and shapes to image",
    ],
    id: [
      "gambar di atas foto",
      "coret coret foto online",
      "tambah anotasi ke gambar",
      "edit foto dengan gambar tangan",
      "tulis di atas gambar online",
      "edit gambar pakai pensil online",
      "tambah panah dan bentuk ke gambar",
      "coret foto online gratis",
    ],
  },
  "color-picker-image": {
    en: [
      "color picker from image",
      "eyedropper tool online",
      "get hex color from image",
      "image color picker free",
      "pick color code from photo",
      "extract color from picture",
      "color code finder from image",
      "rgb picker from photo",
    ],
    id: [
      "ambil warna dari gambar",
      "cari kode warna dari foto",
      "pipet warna online",
      "deteksi warna dari gambar",
      "ambil kode hex dari foto",
      "cari warna dominan gambar",
      "cek kode rgb dari gambar",
      "pipet warna dari foto online",
    ],
  },
  "metadata-viewer": {
    en: [
      "image metadata viewer",
      "exif data viewer online",
      "view photo exif online",
      "check image metadata free",
      "exif reader online",
      "camera info from photo",
      "gps location from photo exif",
      "view photo capture date",
    ],
    id: [
      "lihat metadata foto",
      "cek data exif foto",
      "lihat lokasi gps dari foto",
      "cek info kamera dari foto",
      "cek exif kamera online",
      "lihat tanggal foto diambil",
      "lihat data teknis foto",
      "cek metadata gambar gratis",
    ],
  },
  "svg-tracer": {
    en: [
      "svg tracer online",
      "image to svg converter",
      "convert png to svg",
      "vectorize image online",
      "raster to vector converter",
      "trace image to vector free",
      "photo to vector converter",
      "convert logo to svg",
    ],
    id: [
      "ubah gambar ke svg",
      "vektorkan gambar online",
      "convert foto ke vector gratis",
      "buat logo vector online",
      "ubah gambar jadi file vector",
      "trace logo ke svg online",
      "vektor gambar tanpa aplikasi",
    ],
  },
  watermark: {
    en: [
      "add watermark to image",
      "watermark maker online",
      "photo watermark tool free",
      "text watermark generator",
      "logo watermark on image",
      "protect photo with watermark",
      "bulk watermark images online",
      "add copyright to photo",
    ],
    id: [
      "tambah watermark foto",
      "buat watermark online",
      "kasih watermark ke gambar",
      "watermark foto gratis",
      "buat watermark logo online",
      "pasang watermark ke banyak foto",
      "watermark teks di foto online",
      "lindungi foto dengan watermark",
    ],
  },
  twibbon: {
    en: [
      "twibbon maker",
      "twibbon generator free",
      "campaign photo frame maker",
      "twibbon creator online",
      "profile picture frame maker",
      "event photo frame generator",
    ],
    id: [
      "buat twibbon online",
      "frame foto twibbon",
      "twibbon gratis online",
      "bikin twibbon sendiri",
      "twibbon acara online",
      "buat bingkai foto kampanye online",
    ],
  },
  "device-mockup": {
    en: [
      "device mockup generator",
      "screenshot mockup maker",
      "phone mockup generator free",
      "laptop mockup generator",
      "browser mockup generator",
      "put screenshot in device frame",
      "app screenshot mockup online",
    ],
    id: [
      "buat mockup perangkat online",
      "mockup hp gratis",
      "bingkai screenshot online",
      "mockup laptop online",
      "generator mockup device",
      "tampilan screenshot di bingkai hp",
    ],
  },
  photobooth: {
    en: [
      "online photobooth",
      "web photobooth free",
      "photo booth camera online",
      "photostrip maker online",
      "photobooth strip generator",
      "webcam photobooth free",
      "take photo online with filters",
    ],
    id: [
      "photobooth online gratis",
      "kamera photobooth online",
      "buat photostrip online",
      "foto strip online gratis",
      "foto pakai kamera laptop online",
      "photobooth gratis tanpa aplikasi",
      "buat foto strip lucu online",
    ],
  },
  "qr-generator": {
    en: [
      "qr code generator",
      "free qr code maker",
      "generate qr code from url",
      "wifi qr code generator",
      "custom qr code with logo",
      "qr code creator free",
      "vcard qr code generator",
      "qr code for business card",
    ],
    id: [
      "buat qr code online",
      "buat kode qr gratis",
      "generator qr code online",
      "qr code wifi gratis",
      "buat qr code untuk wifi",
      "qr code untuk kartu nama online",
      "buat barcode qr gratis",
      "qr code custom dengan logo online",
    ],
  },
  "qr-scanner": {
    en: [
      "qr code scanner online",
      "scan qr code from image",
      "decode qr code online",
      "qr code reader free",
      "upload qr code to scan",
      "qr code decoder online",
      "read qr code from photo",
    ],
    id: [
      "baca qr code online",
      "scan qr code dari gambar",
      "pindai qr code gratis",
      "scan barcode qr dari foto",
      "baca kode qr tanpa aplikasi",
      "upload gambar qr untuk dibaca",
      "decode qr code dari gambar online",
    ],
  },

  "barcode-generator": {
    en: [
      "barcode generator online",
      "free barcode maker",
      "generate code128 barcode",
      "ean13 barcode generator",
      "upc barcode generator",
      "create barcode from text",
      "download barcode png",
      "barcode generator for products",
    ],
    id: [
      "buat barcode online",
      "generator barcode gratis",
      "buat barcode dari teks",
      "barcode untuk produk online",
      "unduh barcode png",
      "buat kode batang online",
      "barcode ean upc gratis",
    ],
  },
  "diagram-maker": {
    en: [
      "diagram maker online",
      "flowchart maker free",
      "draw.io alternative",
      "online whiteboard tool",
      "create flowchart online",
      "diagram editor free",
      "export diagram to png svg pdf",
      "mind map maker online",
      "org chart maker free",
      "wireframe tool online",
      "custom diagram creator",
    ],
    id: [
      "buat diagram online",
      "buat flowchart online",
      "alternatif draw.io gratis",
      "papan tulis online gratis",
      "editor diagram bebas",
      "buat bagan online",
      "export diagram ke png pdf",
      "buat mind map online",
      "buat struktur organisasi online",
      "alat wireframe online",
      "buat diagram custom gratis",
    ],
  },
  "code-to-image": {
    en: [
      "code to image",
      "code screenshot generator",
      "carbon.sh alternative",
      "ray.so alternative",
      "beautiful code screenshots",
      "syntax highlighted code image",
      "code snippet to png",
      "share code as image",
      "code image generator free",
      "generate code screenshot online",
    ],
    id: [
      "buat screenshot kode online",
      "ubah kode jadi gambar",
      "alternatif carbon.sh gratis",
      "alternatif ray.so gratis",
      "screenshot kode bagus",
      "buat gambar kode dengan syntax highlight",
      "convert kode ke png",
      "bagikan kode sebagai gambar",
      "generator gambar kode gratis",
    ],
  },
  "favicon-generator": {
    en: [
      "favicon generator online",
      "convert image to favicon",
      "favicon.ico maker",
      "generate favicon from logo",
      "apple touch icon generator",
      "free favicon maker",
      "png to ico converter",
      "website icon generator",
    ],
    id: [
      "buat favicon online",
      "ubah gambar jadi favicon",
      "generator favicon gratis",
      "buat ikon website dari logo",
      "convert png ke ico",
      "buat apple touch icon",
      "favicon.ico online",
    ],
  },

  // --- PDF ---
  "merge-pdf": {
    en: [
      "merge pdf online",
      "combine pdf files free",
      "join multiple pdf into one",
      "pdf merger online",
      "merge pdf without watermark",
      "combine pdf documents online",
      "free pdf joiner",
      "merge pdf files in order",
    ],
    id: [
      "gabung pdf online",
      "gabungkan file pdf gratis",
      "satukan beberapa pdf jadi satu",
      "gabung pdf tanpa watermark",
      "penggabung pdf online",
      "gabungkan dokumen pdf gratis",
      "gabung pdf sesuai urutan",
    ],
  },
  "split-pdf": {
    en: [
      "split pdf online",
      "extract pages from pdf",
      "pdf splitter free",
      "separate pdf pages",
      "split pdf into two files",
      "extract pdf page range",
      "divide pdf document online",
    ],
    id: [
      "pisah pdf online",
      "ekstrak halaman pdf",
      "pemisah pdf gratis",
      "pisahkan halaman pdf",
      "pisah pdf jadi dua file",
      "ambil halaman tertentu dari pdf",
      "potong dokumen pdf online",
    ],
  },
  "image-to-pdf": {
    en: [
      "image to pdf converter",
      "convert jpg to pdf online",
      "png to pdf converter free",
      "combine images into pdf",
      "photo to pdf converter",
      "multiple images to one pdf",
      "convert picture to pdf online",
    ],
    id: [
      "convert gambar ke pdf",
      "ubah jpg ke pdf online",
      "convert foto ke pdf gratis",
      "gabungkan gambar jadi pdf",
      "ubah beberapa foto jadi satu pdf",
      "convert png ke pdf online",
      "jadikan gambar file pdf",
    ],
  },

  "pdf-editor": {
    en: [
      "edit pdf online",
      "pdf editor free",
      "add text to pdf",
      "highlight pdf online",
      "redact pdf online",
      "whiteout pdf",
      "draw on pdf online",
      "annotate pdf free",
      "fill and edit pdf",
      "sign pdf online",
    ],
    id: [
      "edit pdf online",
      "editor pdf gratis",
      "tambah teks ke pdf",
      "highlight pdf online",
      "hapus tulisan di pdf",
      "coret pdf online",
      "gambar di atas pdf",
      "anotasi pdf gratis",
      "edit dan isi pdf online",
      "tanda tangan pdf online",
    ],
  },

  // --- UNIT ---
  "unit-converter": {
    en: [
      "unit converter online",
      "convert length weight temperature",
      "metric to imperial converter",
      "convert km to miles",
      "unit converter free tool",
      "convert volume area speed",
      "convert celsius to fahrenheit",
    ],
    id: [
      "konversi satuan online",
      "ubah satuan panjang berat",
      "konversi ukuran gratis",
      "konversi panjang berat suhu",
      "ubah km ke mil online",
      "konversi celcius ke fahrenheit",
      "alat konversi satuan gratis",
      "tangga satuan panjang berat volume",
      "konversi km hm dam m dm cm mm",
      "konversi liter ke ml",
    ],
  },
  "physics-converter": {
    en: [
      "physics unit converter",
      "convert newton to kilonewton",
      "convert joule to calorie",
      "speed force energy power pressure converter",
      "convert watt to horsepower",
      "convert pascal to bar atm",
      "physics units online calculator",
    ],
    id: [
      "konversi satuan fisika",
      "konversi gaya usaha energi daya tekanan",
      "ubah newton ke kilonewton",
      "konversi joule ke kalori",
      "konversi watt ke hp pk",
      "konversi pascal ke bar atm",
      "alat hitung fisika online",
    ],
  },
  "data-converter": {
    en: [
      "data storage converter",
      "convert mb to gb",
      "byte converter online",
      "kb mb gb tb converter",
      "digital storage unit converter",
      "file size converter free",
      "convert bytes to gigabytes",
    ],
    id: [
      "konversi ukuran file",
      "ubah satuan penyimpanan data",
      "konversi byte ke gb",
      "ubah mb ke gb online",
      "konversi kb ke mb gratis",
      "hitung ukuran penyimpanan digital",
      "alat konversi byte online",
    ],
  },

  // --- TEXT ---
  "case-converter": {
    en: [
      "case converter online",
      "text case converter",
      "uppercase to lowercase converter",
      "title case generator",
      "convert text to sentence case",
      "camel case converter",
      "snake case generator online",
      "capitalize text online",
    ],
    id: [
      "ubah huruf besar kecil",
      "ubah teks jadi huruf kapital",
      "konversi teks online",
      "ubah teks jadi title case",
      "konversi teks ke huruf kecil",
      "ubah teks ke camel case online",
      "kapitalisasi teks otomatis",
    ],
  },
  "word-counter": {
    en: [
      "word counter online",
      "character counter online",
      "count words in text",
      "text length counter",
      "word count tool free",
      "sentence and paragraph counter",
      "count characters in paragraph",
    ],
    id: [
      "hitung jumlah kata",
      "hitung karakter teks online",
      "penghitung kata gratis",
      "hitung kalimat dan paragraf",
      "cek jumlah karakter tulisan",
      "hitung panjang teks online",
    ],
  },
  "lorem-ipsum": {
    en: [
      "lorem ipsum generator",
      "placeholder text generator",
      "dummy text generator online",
      "generate lorem ipsum free",
      "fake text generator",
      "filler text generator online",
      "sample text generator for design",
    ],
    id: [
      "generator teks lorem ipsum",
      "buat teks dummy online",
      "teks placeholder gratis",
      "buat teks isian desain",
      "teks pengisi konten gratis",
      "buat kalimat dummy online",
    ],
  },
  "markdown-previewer": {
    en: [
      "markdown previewer online",
      "markdown to html converter",
      "live markdown editor",
      "preview markdown online",
      "md file viewer free",
      "markdown editor online",
      "render markdown live",
    ],
    id: [
      "preview markdown online",
      "editor markdown gratis",
      "lihat hasil markdown online",
      "ubah markdown ke html online",
      "tulis dan lihat markdown langsung",
      "cek tampilan file md online",
    ],
  },
  "text-diff": {
    en: [
      "text diff checker",
      "compare two texts online",
      "diff tool free",
      "text comparison tool",
      "find difference between text",
      "line by line text compare",
      "compare documents online",
    ],
    id: [
      "bandingkan dua teks online",
      "cek perbedaan teks",
      "perbandingan dokumen online",
      "cek selisih dua dokumen",
      "bandingkan kode program online",
      "cari kata yang berubah di teks",
    ],
  },
  "slug-generator": {
    en: [
      "slug generator online",
      "url slug generator",
      "convert title to slug",
      "text to url friendly slug",
      "generate seo friendly slug",
      "slugify text online",
      "wordpress slug generator",
    ],
    id: [
      "buat slug url online",
      "ubah judul jadi slug",
      "generator slug gratis",
      "buat url ramah seo",
      "slug artikel online",
      "ubah teks jadi url-friendly",
    ],
  },

  // --- MATH ---
  "percentage-calculator": {
    en: [
      "percentage calculator online",
      "calculate percentage free",
      "percent increase decrease calculator",
      "percentage of a number calculator",
      "discount percentage calculator",
      "percentage change calculator",
    ],
    id: [
      "hitung persen online",
      "kalkulator persen gratis",
      "hitung diskon persen",
      "hitung kenaikan persen online",
      "kalkulator diskon belanja",
      "hitung persen dari angka",
    ],
  },
  "age-calculator": {
    en: [
      "age calculator online",
      "calculate age from date of birth",
      "birthday age calculator",
      "age in years months days calculator",
      "how old am i calculator",
      "date of birth age calculator",
    ],
    id: [
      "hitung umur online",
      "kalkulator usia gratis",
      "hitung umur dari tanggal lahir",
      "kalkulator ulang tahun gratis",
      "cek umur dalam hari online",
      "hitung usia dari tanggal lahir online",
    ],
  },
  "bmi-calculator": {
    en: [
      "bmi calculator online",
      "body mass index calculator",
      "calculate bmi metric imperial",
      "ideal weight calculator",
      "bmi chart calculator free",
      "check bmi online",
    ],
    id: [
      "hitung bmi online",
      "kalkulator berat badan ideal",
      "cek indeks massa tubuh",
      "kalkulator imt online",
      "cek berat badan ideal gratis",
      "hitung bmi metrik dan imperial",
    ],
  },
  "tip-calculator": {
    en: [
      "tip calculator online",
      "split bill calculator",
      "calculate tip and split bill",
      "bill splitter tool free",
      "gratuity calculator online",
      "restaurant bill calculator",
    ],
    id: [
      "hitung tip restoran",
      "kalkulator patungan bayar",
      "bagi tagihan online",
      "hitung tip makan online",
      "kalkulator bagi rata tagihan",
      "hitung service charge restoran",
    ],
  },
  "split-bill": {
    en: [
      "split bill calculator",
      "bill splitter online",
      "split bill by item",
      "split bill by percentage",
      "restaurant bill splitter free",
      "divide bill among friends",
      "split expenses calculator",
      "group bill calculator online",
    ],
    id: [
      "kalkulator split bill",
      "bagi tagihan online",
      "hitung patungan makan",
      "split bill per item",
      "bagi tagihan berdasarkan persen",
      "kalkulator patungan bareng teman",
      "hitung urunan bayar tagihan",
      "aplikasi bagi tagihan gratis",
    ],
  },
  "random-picker": {
    en: [
      "random picker online",
      "dice roller online",
      "coin flip online",
      "random number generator free",
      "random name picker",
      "pick random item from list",
      "online decision maker tool",
    ],
    id: [
      "pengacak online",
      "lempar dadu online",
      "lempar koin online",
      "generator angka acak gratis",
      "pemilih nama acak",
      "pilih acak dari daftar",
      "alat pengambil keputusan acak",
    ],
  },
  "date-difference-calculator": {
    en: [
      "date difference calculator",
      "days between two dates calculator",
      "calculate difference between dates",
      "date duration calculator online",
      "how many days between dates",
      "date calculator online free",
    ],
    id: [
      "hitung selisih tanggal online",
      "kalkulator jarak antar tanggal",
      "hitung jumlah hari antara dua tanggal",
      "kalkulator durasi tanggal",
      "hitung selisih hari online",
      "kalkulator tanggal gratis",
    ],
  },
  "hpp-calculator": {
    en: [
      "hpp calculator online",
      "cost of production calculator",
      "cost of goods sold calculator",
      "manufacturing cost calculator free",
      "calculate cost per unit online",
      "product pricing calculator umkm",
    ],
    id: [
      "hitung hpp online",
      "kalkulator harga pokok produksi",
      "kalkulator harga pokok penjualan",
      "cara menghitung hpp umkm",
      "hitung biaya produksi per unit",
      "kalkulator hpp gratis",
      "hitung modal produksi dan harga jual",
    ],
  },
  "profit-margin-calculator": {
    en: [
      "profit margin calculator online",
      "markup calculator free",
      "margin vs markup calculator",
      "calculate profit percentage online",
      "selling price calculator from cost",
    ],
    id: [
      "hitung margin keuntungan",
      "kalkulator markup online",
      "hitung persen keuntungan jualan",
      "kalkulator margin dan markup",
      "cara hitung harga jual dari modal",
    ],
  },
  "discount-calculator": {
    en: [
      "discount calculator online",
      "stacked discount calculator",
      "calculate price after discount",
      "double discount calculator free",
      "percent off calculator",
    ],
    id: [
      "kalkulator diskon online",
      "hitung diskon bertingkat",
      "hitung harga setelah diskon",
      "kalkulator diskon 2 kali",
      "cek harga diskon gratis",
    ],
  },
  "tax-calculator": {
    en: [
      "tax calculator online",
      "vat calculator free",
      "ppn calculator indonesia",
      "calculate tax inclusive exclusive",
      "sales tax calculator online",
    ],
    id: [
      "kalkulator pajak online",
      "hitung ppn online",
      "kalkulator ppn 11 persen",
      "hitung harga sebelum dan sesudah pajak",
      "cara hitung dpp ppn",
    ],
  },
  "break-even-calculator": {
    en: [
      "break even point calculator",
      "bep calculator online",
      "calculate break even units",
      "contribution margin calculator free",
      "business break even analysis tool",
    ],
    id: [
      "kalkulator titik impas",
      "hitung bep online",
      "kalkulator break even point",
      "cara menghitung titik impas usaha",
      "hitung bep unit dan rupiah",
    ],
  },
  "zakat-calculator": {
    en: [
      "zakat calculator online",
      "zakat fitrah calculator",
      "zakat maal calculator",
      "zakat on income calculator",
      "gold silver zakat calculator",
      "nisab calculator free",
    ],
    id: [
      "kalkulator zakat online",
      "hitung zakat fitrah",
      "hitung zakat maal",
      "hitung zakat penghasilan",
      "kalkulator zakat emas",
      "cara hitung nisab zakat",
      "kalkulator zakat gratis",
    ],
  },

  // --- COLOR ---
  "color-picker": {
    en: [
      "color picker online",
      "hex color picker",
      "rgb color picker free",
      "pick color code online",
      "color code generator",
      "hsl color picker tool",
      "cmyk color picker online",
    ],
    id: [
      "pilih warna online",
      "cari kode warna hex",
      "alat pemilih warna gratis",
      "cari kode warna rgb online",
      "alat konversi kode warna",
      "pilih warna hex gratis",
      "cek kode warna cmyk online",
    ],
  },
  "color-palette": {
    en: [
      "color palette generator",
      "generate color scheme online",
      "hex color palette maker",
      "random color palette generator",
      "color combination tool free",
      "palette generator for design",
      "generate matching colors",
    ],
    id: [
      "buat palet warna online",
      "generator skema warna gratis",
      "kombinasi warna otomatis",
      "buat kombinasi warna desain",
      "generator warna acak online",
      "cari palet warna serasi",
      "buat skema warna website",
    ],
  },
  "gradient-generator": {
    en: [
      "css gradient generator",
      "linear gradient maker online",
      "radial gradient generator",
      "gradient color picker",
      "generate css background gradient",
      "gradient css code generator",
    ],
    id: [
      "buat gradasi warna css",
      "generator gradasi warna online",
      "kode css gradient gratis",
      "buat kode gradasi css online",
      "kombinasi warna gradient css",
    ],
  },
  "contrast-checker": {
    en: [
      "color contrast checker",
      "wcag contrast checker online",
      "accessibility contrast ratio tool",
      "check text background contrast",
      "contrast ratio calculator free",
      "aa aaa contrast checker",
    ],
    id: [
      "cek kontras warna online",
      "alat cek aksesibilitas warna",
      "rasio kontras teks gratis",
      "cek rasio kontras teks online",
      "cek warna sesuai standar wcag",
    ],
  },

  // --- DEV ---
  "json-formatter": {
    en: [
      "json formatter online",
      "json beautifier free",
      "json validator online",
      "format json online",
      "minify json online",
      "json pretty print",
      "json editor and viewer",
    ],
    id: [
      "format json online",
      "rapikan json gratis",
      "validasi json online",
      "beautify json online gratis",
      "cek format json valid",
      "perkecil ukuran json online",
      "editor json online gratis",
    ],
  },
  "base64-encoder": {
    en: [
      "base64 encoder decoder online",
      "encode text to base64",
      "decode base64 online",
      "base64 to image converter",
      "base64 converter free",
      "encode image to base64",
    ],
    id: [
      "encode teks ke base64",
      "decode base64 online gratis",
      "konversi base64 ke gambar",
      "ubah gambar ke base64",
      "alat konversi base64 online",
    ],
  },
  "password-generator": {
    en: [
      "password generator online",
      "strong random password generator",
      "secure password maker",
      "generate password free",
      "random password generator tool",
      "create strong password online",
    ],
    id: [
      "buat password acak",
      "generator password gratis",
      "buat kata sandi kuat online",
      "buat sandi acak online",
      "generator kata sandi aman",
      "buat password sulit ditebak",
    ],
  },
  "hash-generator": {
    en: [
      "hash generator online",
      "md5 hash generator",
      "sha256 hash calculator",
      "generate hash from text",
      "checksum calculator free",
      "hash text online",
    ],
    id: [
      "generator hash online",
      "hitung md5 sha256 gratis",
      "buat checksum online",
      "hitung hash md5 online",
      "buat checksum file gratis",
      "generator sha256 online",
    ],
  },
  "timestamp-converter": {
    en: [
      "unix timestamp converter",
      "epoch converter online",
      "timestamp to date converter",
      "convert unix time to date",
      "epoch time calculator",
      "unix time to human readable date",
    ],
    id: [
      "konversi timestamp online",
      "ubah unix time ke tanggal",
      "kalkulator epoch time",
      "ubah epoch time ke tanggal",
      "konversi waktu unix online",
      "kalkulator waktu unix gratis",
    ],
  },
  "url-encoder": {
    en: [
      "url encoder decoder online",
      "encode url free",
      "decode url string online",
      "percent encoding tool",
      "uri encoder online",
      "encode special characters in url",
    ],
    id: [
      "encode url online",
      "decode url gratis",
      "alat encode karakter url",
      "encode karakter khusus url",
      "decode string url online",
      "alat konversi url gratis",
    ],
  },
  "uuid-generator": {
    en: [
      "uuid generator online",
      "generate random uuid v4",
      "guid generator free",
      "bulk uuid generator",
      "unique id generator tool",
      "generate multiple uuids",
    ],
    id: [
      "generator uuid online",
      "buat id unik gratis",
      "buat uuid v4 online",
      "buat guid online gratis",
      "generator id unik banyak sekaligus",
      "buat uuid random online",
    ],
  },
  "regex-tester": {
    en: [
      "regex tester online",
      "regular expression tester",
      "test regex pattern free",
      "regex match checker",
      "javascript regex tester online",
      "regex pattern debugger",
    ],
    id: [
      "tester regex online",
      "uji ekspresi reguler gratis",
      "cek pola regex online",
      "cek pola ekspresi reguler",
      "uji regex javascript online",
      "debug regex pattern gratis",
    ],
  },
  "number-base-converter": {
    en: [
      "number base converter",
      "binary to decimal converter",
      "hex to decimal converter online",
      "convert binary hex octal",
      "base converter tool free",
      "decimal to binary converter online",
    ],
    id: [
      "konversi basis angka",
      "ubah biner ke desimal",
      "konversi angka heksadesimal",
      "konversi desimal ke biner online",
      "ubah heksadesimal ke desimal",
      "konversi biner oktal heksadesimal",
    ],
  },
  "jwt-decoder": {
    en: [
      "jwt decoder online",
      "decode jwt token",
      "jwt token viewer",
      "inspect jwt claims",
      "json web token decoder free",
      "verify jwt payload online",
    ],
    id: [
      "decode token jwt online",
      "lihat isi jwt gratis",
      "cek payload jwt online",
      "cek isi token jwt online",
      "lihat header dan payload jwt",
      "decode json web token gratis",
    ],
  },
  "html-viewer": {
    en: [
      "html viewer online",
      "html previewer free",
      "render html code online",
      "html to preview converter",
      "live html editor online",
      "test html code online",
    ],
    id: [
      "preview html online",
      "lihat hasil kode html",
      "editor html online gratis",
      "jalankan kode html online",
      "tes tampilan html langsung",
      "editor html live gratis",
    ],
  },
  "csv-json-converter": {
    en: [
      "csv to json converter",
      "json to csv converter online",
      "convert csv to json free",
      "csv json converter online",
      "convert spreadsheet to json",
      "csv to json online tool",
    ],
    id: [
      "convert csv ke json",
      "ubah json ke csv online",
      "konversi csv ke json gratis",
      "convert excel ke json",
      "konverter csv json online",
      "ubah data csv jadi json",
    ],
  },
  "meta-tag-generator": {
    en: [
      "meta tag generator online",
      "seo meta tags generator",
      "open graph tag generator",
      "twitter card generator",
      "meta description generator",
      "generate html meta tags",
      "seo tag generator free",
      "google search preview tool",
    ],
    id: [
      "generator meta tag online",
      "buat meta tag seo gratis",
      "generator open graph tag",
      "buat meta description online",
      "generator tag html seo",
      "preview hasil pencarian google",
      "generator twitter card",
    ],
  },

  // --- PRODUCTIVITY ---
  "schedule-maker": {
    en: [
      "schedule maker online",
      "class schedule generator",
      "work shift schedule maker",
      "weekly schedule template free",
      "timetable maker online",
      "schedule to pdf",
      "printable schedule generator",
    ],
    id: [
      "pembuat jadwal online",
      "generator jadwal pelajaran",
      "buat jadwal kerja shift",
      "template jadwal mingguan gratis",
      "jadwal kuliah online",
      "export jadwal ke pdf",
      "jadwal piket online",
    ],
  },
  "broadcast-maker": {
    en: [
      "broadcast message maker",
      "whatsapp broadcast template",
      "promo message generator",
      "announcement text generator",
      "invitation message maker online",
      "broadcast template free",
    ],
    id: [
      "pembuat pesan broadcast",
      "template broadcast whatsapp",
      "generator pesan promo",
      "template pengumuman online",
      "buat pesan undangan online",
      "template broadcast gratis",
    ],
  },
  "voice-to-text": {
    en: [
      "voice to text online",
      "speech to text free",
      "voice recognition transcription",
      "dictate text online",
      "speak to text converter",
      "real time speech transcription",
    ],
    id: [
      "ubah suara ke teks",
      "voice to text bahasa indonesia",
      "transkrip suara online gratis",
      "rekam suara jadi teks",
      "dikte teks online",
      "speech to text indonesia",
    ],
  },
  "text-to-voice": {
    en: [
      "text to speech online",
      "text to voice converter",
      "free text to speech",
      "read text aloud online",
      "convert text file to speech",
      "natural voice reader online",
      "type text and hear it spoken",
      "upload text file to speech",
    ],
    id: [
      "ubah teks ke suara",
      "text to speech bahasa indonesia",
      "baca teks jadi suara online",
      "konversi teks ke suara gratis",
      "upload file teks jadi suara",
      "text to speech gratis",
      "alat pembaca teks online",
    ],
  },
};
